---
- name: Ensure that curl package is installed (Debian)
  apt:
    name: curl
    state: installed
    update_cache: yes
    cache_valid_time: 600
  when: ansible_os_family == "Debian"

- name: Ensure that python packages are installed for advanced (Debian)
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 600
  with_items:
      - python3
      - python3-pip
  when: ansible_os_family == "Debian" and ssh_login_notifications_slack_app_oauth is defined

- name: Install required Slack Client for python3
  pip:  executable=pip3 name=SlackClient
  when: ansible_os_family == "Debian" and ssh_login_notifications_slack_app_oauth is defined


- fail:
    msg: Sorry we currently do not support advanced notifications on RedHat
  when: ansible_os_family == "RedHat" and ssh_login_notifications_slack_app_oauth is defined


- name: Ensure that curl package is installed (RedHat)
  yum:
    name: curl
    state: installed
    update_cache: yes
  when: ansible_os_family == "RedHat"


- name: Create Slack notification script
  template:
    src: send_slack_on_ssh_login.sh.j2
    dest: /usr/local/bin/send_slack_on_ssh_login.sh
    mode: 0744


- name: Add the extra feature processing script
  template:
    src: ../src/ssh-login-audit.py
    dest: /usr/local/bin/ssh-login-audit.py
    mode: 0744


- name: Add the extra feature processing script
  template:
    src: ../src/utils.py
    dest: /usr/local/bin/utils.py
    mode: 0744


- name: Enable Slack notification script in SSHd PAM config file
  lineinfile:
    dest: /etc/pam.d/sshd
    line: "session optional pam_exec.so /usr/local/bin/send_slack_on_ssh_login.sh"
