---
- name: "sanity checks"
  fail:
    msg: "The 'ssh_login_notifications_slack_app_channel' variable must be a list of strings (or not defined at all), currently: {{ ssh_login_notifications_slack_app_channel }}"
  when: ssh_login_notifications_slack_app_channel is defined and (ssh_login_notifications_slack_app_channel is not iterable or ssh_login_notifications_slack_app_channel is string)

- name: "sanity checks"
  fail:
    msg: The 'ssh_login_notifications_auditapp_keys' variable must be a list of strings
  when: ssh_login_notifications_auditapp_keys is defined and (ssh_login_notifications_auditapp_keys is not iterable or ssh_login_notifications_auditapp_keys is string)

- name: "sanity checks"
  fail:
    msg: The 'ssh_login_notifications_auditapp_report_key' variable must be a string
  when: ssh_login_notifications_auditapp_report_key is defined and ssh_login_notifications_auditapp_report_key is not string

- name: "sanity checks"
  fail:
    msg: The 'ssh_login_notifications_auditapp_endpoint' variable must be defined if we're using the Audit App
  when: ssh_login_notifications_auditapp_keys is defined and ssh_login_notifications_auditapp_endpoint is not defined

- name: Ensure that curl package is installed (Debian)
  apt:
    name: curl
    state: installed
    update_cache: yes
    cache_valid_time: 600
  when: ansible_os_family == "Debian"

- name: Ensure that python packages are installed for advanced (Debian)
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 600
  with_items:
      - python3
      - python3-pip
  when: ansible_os_family == "Debian" and ssh_login_notifications_slack_app_oauth is defined

- name: Install required Slack Client for python3
  pip:  executable=pip3 name=SlackClient
  when: ansible_os_family == "Debian" and ssh_login_notifications_slack_app_oauth is defined


- name: "sanity checks for the advanced support"
  fail:
    msg: Sorry we currently do not support advanced notifications on RedHat
  when: ansible_os_family == "RedHat" and ssh_login_notifications_slack_app_oauth is defined


- name: Ensure that curl package is installed (RedHat)
  yum:
    name: curl
    state: installed
    update_cache: yes
  when: ansible_os_family == "RedHat"


- name: Create Slack notification script
  template:
    src: send_slack_on_ssh_login.sh.j2
    dest: /usr/local/bin/send_slack_on_ssh_login.sh
    mode: 0744


- name: Add the extra feature processing script
  copy:
    src: ../src/ssh-login-audit
    dest: /var/lib/
    mode: 0744

#- name: Add the extra feature processing script (the Audit App version)
#  copy:
#    src: ../src/ssh-login-audit-app.py
#    dest: /var/lib/ssh-login-audit/ssh-login-audit-app.py
#    mode: 0744
#
#- name: Add the extra feature processing script (the Audit App version)
#  copy:
#    src: ../src/utils.py
#    dest: /var/lib/ssh-login-audit/utils.py
#    mode: 0744

- name: Add the extra feature processing script
  template:
    src: ../src/utils.py
    dest: /usr/local/bin/utils.py
    mode: 0744


- name: Enable Slack notification script in SSHd PAM config file
  lineinfile:
    dest: /etc/pam.d/sshd
    line: "session optional pam_exec.so /usr/local/bin/send_slack_on_ssh_login.sh"
